// This file is generated by FlutterFire CLI.
// You will need to run `flutterfire configure` in your terminal
// after setting up your Firebase project to generate the actual content.

// IMPORTANT: After pasting this, run 'flutterfire configure' in your terminal
// from the root of your project to generate the actual Firebase options.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform, kIsWeb;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
         apiKey: "AIzaSyD-2VKuhGFrPcJ0zPPWblUkWAoDU_PO0wg",
        authDomain: "edunjema3-cc49c.firebaseapp.com",
         projectId: "edunjema3-cc49c",
        storageBucket: "edunjema3-cc49c.firebasestorage.app",
        messagingSenderId: "576942726328",
        appId: "1:576942726328:web:37b6cb93c67721b4d6284d",
        measurementId: "G-M1YF7DSK87"
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
           apiKey: "AIzaSyD-2VKuhGFrPcJ0zPPWblUkWAoDU_PO0wg",
           authDomain: "edunjema3-cc49c.firebaseapp.com",
          projectId: "edunjema3-cc49c",
          storageBucket: "edunjema3-cc49c.firebasestorage.app",
          messagingSenderId: "576942726328",
          appId: "1:576942726328:web:37b6cb93c67721b4d6284d",
          measurementId: "G-M1YF7DSK87"
        );
      case TargetPlatform.iOS:
        return const FirebaseOptions(
          apiKey: 'YOUR_IOS_API_KEY',
          appId: 'YOUR_IOS_APP_ID',
          messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
          projectId: 'edunjema3-cc49c',
          storageBucket: 'YOUR_STORAGE_BUCKET',
          iosClientId: 'YOUR_IOS_CLIENT_ID',
          iosBundleId: 'YOUR_IOS_BUNDLE_ID',
        );
      case TargetPlatform.macOS:
        return const FirebaseOptions(
          apiKey: 'YOUR_MACOS_API_KEY',
          appId: 'YOUR_MACOS_APP_ID',
          messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
          projectId: 'edunjema3-cc49c',
          storageBucket: 'YOUR_STORAGE_BUCKET',
          iosClientId: 'YOUR_MACOS_CLIENT_ID',
          iosBundleId: 'YOUR_MACOS_BUNDLE_ID',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
